import type {
  Course,
  DailyTaskUnit,
  GScore,
  LeaderboardEntry,
  Lead,
  Lesson,
  Module,
  ParentReport,
  Payment,
  Quiz,
  Student,
} from "@/lib/types";

export const courses: Course[] = [
  {
    id: "course-bridge",
    title: "SSC-to-HSC Science Bridge Course",
    slug: "ssc-to-hsc-science-bridge",
    description:
      "An 8-week NCTB-aligned transition programme that helps SSC graduates move smoothly into HSC Science through Physics, Chemistry, Higher Mathematics, Biology readiness, academic English support, and guided study discipline for Bangla Version and English Version learners.",
    courseType: "bridge",
    targetBatch: "HSC 2028",
    versionSupport: "Both",
    mode: "hybrid",
    durationWeeks: 8,
    price: 6500,
    isPublished: true,
    highlights: [
      "Diagnostic baseline to identify SSC-level gaps before HSC Science begins",
      "HSC Science readiness in Physics, Chemistry, Higher Mathematics, and Biology",
      "Daily Task Units that build study discipline and submission habits",
      "Weekly quiz and recovery cycle for steady academic correction",
      "GScore progress visibility for students and parents",
      "Printed learning materials and guided practice for Bangla Version and English Version learners",
    ],
    materials: [
      "GRADE CM: Conceptual Mastery Notes",
      "GRADE Lens: Visual Concept Workbook",
      "GRADE Flash: Formula and Concept Flashcards",
      "GRADE Track: Study Planner and Progress Tracker",
      "GRADE Innovate: Science Curiosity and Project Workbook",
    ],
    weeklyStructure: [
      "Week 1: Orientation, diagnostic baseline, and SSC-to-HSC transition mindset",
      "Week 2: Mathematical tools for HSC Science: algebra, graph reading, functions, units",
      "Week 3: Physics foundation: measurement, vectors, motion, force, graph interpretation",
      "Week 4: Chemistry foundation: atomic structure, mole concept, periodic trends, bonding basics",
      "Week 5: Higher Mathematics readiness: functions, trigonometry, logarithms, problem-solving habits",
      "Week 6: Biology readiness: cell, biomolecules, genetics basics, scientific terminology",
      "Week 7: Integrated Science application: mixed problems, data interpretation, written explanation",
      "Week 8: Final review, HSC readiness assessment, personal study plan, next-stage guidance",
    ],
  },
  {
    id: "course-crash",
    title: "HSC 26 Exam Ready Crash Course",
    slug: "hsc-26-exam-ready",
    description:
      "An 8-week final preparation system for HSC 2026 students with board-focused revision, tests, doubt clearing, and accountability.",
    courseType: "exam_ready",
    targetBatch: "HSC 2026",
    versionSupport: "Both",
    mode: "hybrid",
    durationWeeks: 8,
    price: 8500,
    isPublished: true,
    highlights: [
      "Recorded revision lessons",
      "Live problem solving",
      "Weekly board-style tests",
      "Prioritised revision map",
      "Teacher review and GScore",
    ],
    materials: ["GRADE QB", "GRADE Draw", "GRADE Flash", "GRADE Track", "GRADE Script", "GRADE Map"],
    weeklyStructure: [
      "Diagnostic gap check",
      "High-priority chapter revision",
      "Board question practice",
      "Weekly timed tests",
      "Parent-ready progress report",
    ],
  },
];

export const modules: Module[] = [
  {
    id: "module-bridge-1",
    courseId: "course-bridge",
    title: "Orientation and Baseline",
    description: "Start HSC Science with a clear baseline, routine, and study system.",
    orderIndex: 1,
  },
  {
    id: "module-bridge-2",
    courseId: "course-bridge",
    title: "Physics Concept Bridge",
    description: "Core language, units, graphs, and problem setup for HSC Physics.",
    orderIndex: 2,
  },
  {
    id: "module-crash-1",
    courseId: "course-crash",
    title: "Board Revision Sprint",
    description: "High-yield board-style practice and time-managed revision.",
    orderIndex: 1,
  },
];

export const lessons: Lesson[] = [
  {
    id: "lesson-bridge-1",
    courseId: "course-bridge",
    moduleId: "module-bridge-1",
    title: "How HSC Science Changes After SSC",
    description: "A practical map of the jump from memorised SSC content to HSC concept and problem solving.",
    lessonType: "video",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    orderIndex: 1,
    isPreview: true,
    requiresPreviousCompletion: false,
    status: "completed",
  },
  {
    id: "lesson-bridge-2",
    courseId: "course-bridge",
    moduleId: "module-bridge-1",
    title: "Baseline Diagnostic Briefing",
    description: "Understand how the diagnostic quiz creates the first recovery map.",
    lessonType: "quiz",
    orderIndex: 2,
    isPreview: false,
    requiresPreviousCompletion: true,
    status: "available",
  },
  {
    id: "lesson-bridge-3",
    courseId: "course-bridge",
    moduleId: "module-bridge-2",
    title: "Vectors, Units, and Graph Thinking",
    description: "A bridge lesson for the common places students get stuck in early HSC Physics.",
    lessonType: "video",
    orderIndex: 3,
    isPreview: false,
    requiresPreviousCompletion: true,
    status: "requires_quiz",
  },
  {
    id: "lesson-crash-1",
    courseId: "course-crash",
    moduleId: "module-crash-1",
    title: "Final 8-Week Revision Map",
    description: "Plan high-yield chapters, board pattern practice, and weekly test rhythm.",
    lessonType: "video",
    orderIndex: 1,
    isPreview: true,
    requiresPreviousCompletion: false,
    status: "completed",
  },
];

export const students: Student[] = [
  {
    id: "student-1",
    profileId: "profile-student-1",
    fullName: "Ariyan Rahman",
    studentCode: "GRADE-2601",
    version: "Bangla Version",
    classLevel: "Post-SSC",
    currentBatch: "Bridge BV Batch A",
    institution: "Dhaka Residential Model College",
    guardianName: "Mahmud Rahman",
    guardianPhone: "01700000001",
    guardianWhatsapp: "01700000001",
    consentPublicLeaderboard: true,
    status: "active",
  },
  {
    id: "student-2",
    profileId: "profile-student-2",
    fullName: "Nusrat Jahan",
    studentCode: "GRADE-2602",
    version: "English Version",
    classLevel: "HSC",
    currentBatch: "HSC 26 EV Crash",
    institution: "Viqarunnisa Noon School and College",
    guardianName: "Shahana Jahan",
    guardianPhone: "01700000002",
    guardianWhatsapp: "01700000002",
    consentPublicLeaderboard: false,
    status: "active",
  },
];

export const dailyTasks: DailyTaskUnit[] = [
  {
    id: "dtu-1",
    courseId: "course-bridge",
    batchId: "batch-bridge-bv-a",
    lessonId: "lesson-bridge-2",
    title: "Day 3: Baseline Reflection and Graph Practice",
    taskDate: "2026-05-03",
    subject: "Physics",
    chapter: "Measurement and graph basics",
    watchTask: "Watch the baseline briefing lesson",
    readTask: "Read GRADE Lens pages 4-7",
    solveTask: "Solve 8 graph interpretation questions",
    submitTask: "Upload one photo/PDF of solved work",
    reviewTask: "Correct mistakes using the feedback checklist",
    dueAt: "2026-05-03T22:00:00+06:00",
    status: "under_review",
  },
  {
    id: "dtu-2",
    courseId: "course-crash",
    batchId: "batch-crash-ev-a",
    title: "Day 5: Board CQ Sprint",
    taskDate: "2026-05-05",
    subject: "Chemistry",
    chapter: "Organic naming",
    watchTask: "Watch revision clip 2",
    readTask: "Read GRADE Map priority sheet",
    solveTask: "Solve 2 board-style CQs",
    submitTask: "Submit scanned solution",
    reviewTask: "Compare with GRADE Script marking guide",
    dueAt: "2026-05-05T22:00:00+06:00",
    status: "submitted",
  },
];

export const quizzes: Quiz[] = [
  {
    id: "quiz-bridge-baseline",
    courseId: "course-bridge",
    moduleId: "module-bridge-1",
    lessonId: "lesson-bridge-2",
    title: "Bridge Baseline Diagnostic",
    description: "A short diagnostic quiz to identify early gaps before HSC Science starts.",
    quizType: "diagnostic",
    passMark: 50,
    durationMinutes: 15,
    questions: [
      {
        id: "q1",
        questionText: "Which habit best supports the SSC-to-HSC transition?",
        questionType: "mcq",
        optionA: "Watching long lectures only",
        optionB: "Completing daily tasks and reviewing feedback",
        optionC: "Waiting for exams to start",
        optionD: "Skipping concept practice",
        correctAnswer: "B",
        explanation: "GRADE tracks daily effort because consistency is the bridge.",
        marks: 1,
      },
      {
        id: "q2",
        questionText: "GScore includes task completion, quiz score, lesson progress, streak, and teacher effort.",
        questionType: "true_false",
        optionA: "True",
        optionB: "False",
        correctAnswer: "A",
        explanation: "GScore is designed to show more than exam marks.",
        marks: 1,
      },
    ],
  },
];

export const gscores: GScore[] = [
  {
    studentId: "student-1",
    courseId: "course-bridge",
    batchId: "batch-bridge-bv-a",
    weekStart: "2026-05-04",
    weekEnd: "2026-05-10",
    dtuSubmissionRate: 86,
    weeklyQuizPercentage: 78,
    lessonCompletionRate: 67,
    streakScore: 71,
    teacherEffortScore: 90,
    totalGscore: 78.2,
  },
];

export const leaderboard: LeaderboardEntry[] = [
  {
    studentId: "student-1",
    studentName: "Ariyan Rahman",
    consentPublicLeaderboard: true,
    rank: 1,
    totalGscore: 78.2,
    streak: 5,
    label: "Highest streak",
  },
  {
    studentId: "student-2",
    studentName: "Nusrat Jahan",
    consentPublicLeaderboard: false,
    rank: 2,
    totalGscore: 73.5,
    streak: 4,
    label: "Most improved",
  },
];

export const leads: Lead[] = [
  {
    id: "lead-1",
    studentName: "Tanvir Hasan",
    parentName: "Md Hasan",
    studentPhone: "01800000001",
    parentPhone: "01800000002",
    whatsapp: "01800000002",
    email: "tanvir@example.com",
    currentLevel: "SSC completed",
    version: "Bangla Version",
    institution: "Ideal School and College",
    interestedProgramme: "SSC-to-HSC Science Bridge Course",
    preferredMode: "online",
    source: "Facebook",
    status: "new",
    message: "Interested in May batch.",
    notes: "Call after evening.",
    createdAt: "2026-04-25",
  },
];

export const payments: Payment[] = [
  {
    id: "pay-1",
    studentName: "Ariyan Rahman",
    courseTitle: "SSC-to-HSC Science Bridge Course",
    amount: 6500,
    method: "bkash",
    transactionId: "BKS-126778",
    status: "verified",
  },
  {
    id: "pay-2",
    studentName: "Nusrat Jahan",
    courseTitle: "HSC 26 Exam Ready Crash Course",
    amount: 4000,
    method: "nagad",
    transactionId: "NGD-883210",
    status: "pending",
  },
];

export const parentReport: ParentReport = {
  studentName: "Ariyan Rahman",
  courseName: "SSC-to-HSC Science Bridge Course",
  week: "May 4 - May 10, 2026",
  tasksCompleted: 6,
  tasksTotal: 7,
  weeklyTestScore: 78,
  previousWeekScore: 68,
  currentStreak: 5,
  leaderboardRank: 1,
  totalStudents: 24,
  focusThisWeek: "Graph interpretation and disciplined daily submission.",
  focusNextWeek: "Physics units, vectors, and Chemistry mole basics.",
  teacherComment:
    "Ariyan is consistent and improving. He should slow down during problem setup and write units carefully.",
};

export const atRiskStudents = [
  {
    studentName: "Nusrat Jahan",
    course: "HSC 26 Exam Ready Crash Course",
    reason: "Weekly test below 40% twice",
    lastSubmission: "2026-05-02",
    parentContact: "01700000002",
    teacher: "Fahim Sir",
    suggestedAction: "Schedule 20-minute recovery call and assign priority CQ set.",
  },
];
